default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: check
        name: check
        entry: scripts/check.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]
